services:
  mysql:
    image: mariadb:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_PORT}
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  django_app:
    build:
      context: django_app
    command: gunicorn config.wsgi:application --reload
    container_name: django_app
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://0.0.0.0:${DJANGO_PORT}/api/docs/" ]
      interval: 30s
      timeout: 2s
      retries: 15
    ports:
      - 127.0.0.1:${DJANGO_PORT}:${DJANGO_PORT}


volumes:
  db_data:

networks:
  app_network:
    driver: bridge